version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_bun_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bun src/main.ts
